# Generated by Django 5.2.5 on 2025-09-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="image_profile",
            field=models.ImageField(blank=True, upload_to="imagem_cadastro/%Y/%m/"),
        ),
    ]
