# Generated by Django 5.2.5 on 2025-09-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_customuser_image_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="team",
        ),
        migrations.AddField(
            model_name="subject",
            name="team",
            field=models.ManyToManyField(related_name="subjects", to="system.team"),
        ),
    ]
