# Generated by Django 5.2.5 on 2025-12-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_attendance_attendancerecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="value_activity",
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
