# Generated by Django 5.2.5 on 2025-12-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0003_grade_value_activity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="grade",
            old_name="value",
            new_name="value_proof",
        ),
        migrations.AddField(
            model_name="grade",
            name="average",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
